### ISSUE TITLE
HTML & CSS for Post Gallery Page

### ISSUE THREAD

**Issue by donovankeith** [dfmcmurray/la-homeless-data#16]
Wireframe:
![homelessdatahomepage](https://cloud.githubusercontent.com/assets/4267389/16066686/56b2de7a-326a-11e6-8ba2-5c472a7ba8c4.png)

**Comment by donovankeith** [comment]
Started [here](http://codepen.io/donovankeith/pen/YWWzER?editors=1000) - feel free to fork and update.

**Comment by donovanfm** [comment]
The post gallery page is already implemented and can be viewed at http://dfmcmurray.github.io/la-homeless-data/
