### ISSUE TITLE
Datasets to Add from City and County

### ISSUE THREAD

**Issue by JeanneHolm** [dfmcmurray/la-homeless-data#24]
Main repositories of data:
- City of Los Angeles
- https://data.lacity.org/
- County of Los Angeles
- https://data.lacounty.gov/
- State of California
- https://greengov.data.ca.gov/
- U.S. Government
- https://www.data.gov/

General reference documents:
- [County of Los Angeles Homeless Initiative](http://priorities.lacounty.gov/wp-content/uploads/2016/01/Draft-Recommendations.pdf) (PDF)
- [City of Los Angeles Comprehensive Homeless Strategy](http://www.lamayor.org/city-los-angeles-releases-homelessness-strategy-report) (Report)

Specific datasets:
- [Los Angeles County Homeless Count 2016](https://www.lahsa.org/homeless-count/reports) (Report)
- [Los Angeles County Homeless Continuum of Care](https://documents.lahsa.org/Planning/homelesscount/2016/datasummaries/CoC.pdf) (PDF)
- [Employment in the State and County (CA EDD and GovState)](https://data.lacity.org/A-Prosperous-City/CA-EDD-Employment-State-County-GOVSTAT/ecai-dcsz)
  - Seasonally adjusted, monthly employment data for the state and for LA County
- [Set of datasets on employment in the City of Los Angeles](https://data.lacity.org/browse?q=employment)
  1. [Worksource Center Program Performance Outcomes](https://data.lacity.org/A-Prosperous-City/EWDD-Worksource-Center-Program-Performance-Outcome/7w5j-7jjp)
  2. The WSC program, funded through the Workforce Investment Act (WIA); National Emergency Grant (NEG) and other competitive grants, provides employment training and placement services for adults and dislocated workers, with a special emphasis on vulnerable populations, including persons with disabilities, veterans, homeless, English-language learners and older workers. Annual goals are established by California Employment Development Department and the US Department of Labor.
- [Housing and Community Investment Service Locations](https://data.lacity.org/A-Livable-and-Sustainable-City/Housing-Community-Investment-Service-Locations/29cn-rph9)
  - Locations of offices associated with the Los Angeles Housing and Community Investment Department which provide services to city residents.
- [Map of Housing and Community Investment Service Locations](https://data.lacity.org/A-Livable-and-Sustainable-City/HCIDLA-locations-map-gk/uzch-sa9u)
  - Locations of offices associated with the Los Angeles Housing and Community Investment Department that provide services to city residents.
- [County Department of Mental Health (DMH) Provider Directory Mental Health
  Data Lens](https://data.lacounty.gov/Mental-Health/Department-of-Mental-Health-DMH-Provider-Directory/az6g-rq5y)
  - Welcome to the Provider Directory of Publicly Funded Mental Health Providers in the County of Los Angeles for Psychiatric Inpatient and Outpatient Short/Medi-Cal Facilities, Fee-For-Service (FFS) Psychiatric Inpatient Facilities, Community Outreach, Forensic, Residential and Specialized Foster Care Facilities. 
- [Population Poverty and Prevalence Data for Serious Emotional Disturbance (SED) and Serious Mental Illness (SMI) CY 2013 Mental Health](https://data.lacounty.gov/Mental-Health/Population-Poverty-138-FPL-200-FPL-and-Prevalence-/ngfq-buh8)
  -  Population Estimates, prepared by Hedderson Demographic Services and Los Angeles County Internal Services Department Social Services Division. Rates for Mental Illness from the UCLA - California Health Interview Survey (CHIS) were applied to each demographic category to estimate SED/SMI prevalence.
- [Population by Age and Service Area Mental Health Chart](https://data.lacounty.gov/Mental-Health/Population-by-Age-and-Service-Area/ryf9-insf)
  - Population and Prevalence Data for Serious Emotional Disturbance (SED) and Serious Mental Illness (SMI) CY 2013. Source: Data Source: American Community Survey, US Census Bureau and Hedderson Demographic Services, 2014. Prevalence Rate for Mental Illness from the UCLA - California Health Interview Survey (CHIS) was applied to each demographic category.
- [Mental Health Provider Classification Based on Department of Mental Health (DMH) Provider Directory](https://data.lacounty.gov/Mental-Health/Provider-Classification/pxzv-bdfq)
  - Welcome to the Provider Directory of Publicly Funded Mental Health Providers in the County of Los Angeles for Psychiatric Inpatient and Outpatient Short/Doyle/Medi-Cal Facilities, Fee-For-Service (FFS) Psychiatric Inpatient Facilities, Community Outreach, Forensic, Residential and Specialized Foster Care Facilities. This Provider Directory does not include Fee-For-Service Outpatient Provider locations.

**Comment by donovankeith** [comment]
Thanks Jeanne! I reformatted it slightly and added it to our site on the [Data page](https://github.com/dfmcmurray/la-homeless-data/blob/gh-pages/data.md).
